fix: updates RFC 0012 reflecting the current state of the audit scanner.
kubewarden/rfc pull request #29
Opened 2024-03-06 19:44 UTC by jvanz

## Description

Updates the RFC 0012 describing the policy reports used by audit scanner to reflect the latest changes done in the audit scanner to solve some issues when storing the reports on etcd.

2024-03-07 06:09 UTC, fabriziosestito commented on rfc/0012-policy-report.md
> +- `metadata`: this is the usual `meta/v1.ObjectMeta` resource. In the
we added an OwnerReference in the metadata pointing to the resource to allow the report to be garbage collected when the resource is deleted

2024-03-07 06:09 UTC, fabriziosestito commented on rfc/0012-policy-report.md
> +  For example, a `ClusterAdmissionPolicy` named `provileged-containers` will
typo privileged-containers

2024-03-07 06:12 UTC, fabriziosestito commented on rfc/0012-policy-report.md
> +  convention to build the contents of this field: `<[cap|ap]>-<policy name>`.
in the new implementation we use the policy unique name instead (e.g. clusterwide-policyname or namespaced-default-policy)

2024-03-07 06:13 UTC, fabriziosestito commented on rfc/0012-policy-report.md
>  We will have just one `PolicyReport` per Namespace. Depending on the number of
this is outdated

2024-03-08 14:41 UTC, jhkrug requested changes
Minor suggestions and one or two typos.

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +| Update Date  | 03/06/2023                                |
2024?

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +to the `PolicyReport` are equally relevant for the `ClusterPolicyReport`.
```suggestion
Both the `ClusterPolicyReport` and `PolicyReport` serve similar purposes and
are similar in structure. The primary distinction between them lies in their
applicability: one is suited for namespaced resources, the other
for cluster-wide resources. Despite this difference, the
fundamental aspects and the details they convey remain consistent across both
report types. So, the following descriptions and interpretations for
the `PolicyReport` are equally applicable to the `ClusterPolicyReport`.
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +- Policies might be deleted/might be no longer "interested" in the resource:
```suggestion
- Policies might be deleted or might be no longer "interested" in the resource:
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +  and their evaluation results
```suggestion
  the report must be updated to not contain any reference to these policies
  and their evaluation results
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +that are defined inside of the Namespace.
```suggestion
For each Namespace, Kubewarden will find all the policies that are interested
in actions happening in it. This is going to be a mix of
some `ClusterAdmissionPolicy` policies and all the `AdmissionPolicy` policies
that are defined in the Namespace.
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +per audited resource.
```suggestion
All the results are going to be collected into the `PolicyReport` object
defined in the Namespace. There's going to be only one `PolicyReport`
per audited resource.
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +  in use includes:
```suggestion
  in use include:
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +  of the following fields:
```suggestion
  from the following fields:
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +Gatekeeper stores the report results inside of our equivalent of
```suggestion
Gatekeeper stores the report results in our equivalent of
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +We could store the violation details inside of the `status` field of each
```suggestion
We could store the violation details in the `status` field of each
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +are 1) defined inside of the Namespace and 2) are relevant to the policy. Kubewarden
```suggestion
are 1) defined in the Namespace and 2) are relevant to the policy. Kubewarden
```

2024-03-08 14:41 UTC, jhkrug commented on rfc/0012-policy-report.md
> +scans. Hence they will never show inside of the reports.
```suggestion
scans. Hence they will never show in the reports.
```

2024-03-08 14:59 UTC, jvanz commented on rfc/0012-policy-report.md
> +| Update Date  | 03/06/2023                                |
Fixed

2024-03-08 17:11 UTC, jhkrug approved these changes

2024-03-11 10:15 UTC, flavio reviewed
LGTM, I left one really minor comment.

2024-03-11 10:15 UTC, flavio commented on rfc/0012-policy-report.md
> +  with if
```suggestion
  with it
```

2024-03-11 10:15 UTC, flavio commented on rfc/0012-policy-report.md
> +RBAC rules.
I think we should point out that, due to security reasons, a cluster administrator should play safe and give no access to these reports to regular users of the cluster. If they want to relax that, the could give READ access only to the reports that are defined inside of the Namespaces that can be used by the regular users.

What I mean is: if Bob can create resources under the `foo` Namespace, then Bob might get READ access to the reports inside of the `foo` namespace.

2024-03-11 11:59 UTC, viccuad approved these changes
LGTM, modulo the comments from Flavio.

2024-03-12 08:27 UTC, flavio approved these changes
I love the new changes!

2024-03-12 08:28 UTC, flavio commented
@jvanz fix the DCO issue and merge it! :rocket:

2024-03-12 12:13 UTC, merged