fix: updates RFC 0011 reflecting the current state of the audit scanner.
kubewarden/rfc pull request #30
Opened 2024-03-07 02:57 UTC by jvanz

## Description

Updates the RFC 0011 describing how audit scanner performs the scans to reflect the latest changes done in this component.

Related to https://github.com/kubewarden/audit-scanner/issues/209

2024-03-07 06:06 UTC, fabriziosestito commented on rfc/0011-audit-checks.md
> +namespace from the API server, likely in a paginated manner to manage large
remove likely, we are paginating now

2024-03-07 06:06 UTC, fabriziosestito commented on rfc/0011-audit-checks.md
> +The code will overwrite the old `ClusterPolicyReport` instance with a new generated
We don't overwrite but we update the old object field with new data, also I would remove "data kept in memory" as we are keeping the data just for enough time to build the report patch.

2024-03-07 06:06 UTC, fabriziosestito commented on rfc/0011-audit-checks.md
> +the compliance of each resource with the established cluster policies.
I would add that we are cylcing all the resources and auditing the resources one by one against the policies they are targeted by.

2024-03-08 15:11 UTC, jhkrug requested changes
A few suggestions are marked up. One typo as well.

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
>  inside of the `metadata.yml` file of the policy:
```suggestion
in the `metadata.yml` file of the policy:
```

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +Users can still get live data about the rejections/approvals by looking both
```suggestion
Users can still get live data about rejections and approvals by looking both
```

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +* Policies might be hosted on insecure registires/registires with custom TLS
```suggestion
* Policies might be hosted on insecure registries or registries with custom TLS
```

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +out to be true, we can embrace different strategies to mitigate that.
```suggestion
out to be false, we can embrace different strategies to mitigate that.
```

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +configure the other way. Example of policies CRDs with the `backgroundAudit` field:
```suggestion
configures it the other way. Example of policies CRDs with the `backgroundAudit` field:
```

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +By default, the scanner will look at all the namespaces defined inside of the
```suggestion
By default, the scanner will look at all the namespaces defined in the
```

2024-03-08 15:11 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +from the cluster.
```suggestion
No real time audit information is provided by this solution. Users have to rely on
Prometheus metrics and Open Telemetry trace events to have live data coming
from the cluster.
```

2024-03-08 17:31 UTC, jhkrug requested changes
One more 'inside of' change to 'in'.

2024-03-08 17:31 UTC, jhkrug commented on rfc/0011-audit-checks.md
> +Details about the `PolicyReport` format can be found inside of this [RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0012-policy-report.md).
```suggestion
Details about the `PolicyReport` format can be found in this [RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0012-policy-report.md).
```

2024-03-11 10:20 UTC, flavio approved these changes

2024-03-11 11:07 UTC, jhkrug approved these changes
lgtm

2024-03-11 11:59 UTC, viccuad approved these changes
LGTM.

2024-03-11 13:17 UTC, merged