docs: add Policy lifecycle RFC
kubewarden/rfc pull request #44
Opened 2024-12-19 14:48 UTC by fabriziosestito

## Description

Fix #XXX

## Test

To test this pull request, you can run the following commands:

## Additional Information

### Tradeoff

### Potential improvement

2024-12-19 14:52 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +We can use a RWX Persistent Volume to store the cache and share it among all the Policy Server replicas.
elaborate more on the RWX Persistent Volume and what are the requirements to use it

2024-12-19 14:52 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +A leader election mechanism will be implemented to ensure that only one Policy Server instance is acting as a controller at a time.
how do we plan to implement the leader election mechanism?

2024-12-19 14:53 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +The Policy Server will be deployed as a StatefulSet to ensure that each replica has a unique identity.
What is the tradeoff moving away from the Deployment?

2024-12-19 14:53 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +
How does this simplify the main controller code?

2024-12-19 14:55 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +### Shared Policy Cache
what is a cache? mention wasmtime precompiled modules and backward compatibility.

2024-12-20 12:02 UTC, flavio reviewed
Great job, I think we are finally on the right path

2024-12-20 12:02 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +
```suggestion
- As a user, I want to be able to debug what is wrong with namespaced policies that I own without having to bother the administrator of the cluster

```

2024-12-20 12:02 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +A leader election mechanism will be implemented to ensure that only one Policy Server instance is acting as a controller at a time.
We will rely on what the [Kubernetes Leases](https://kubernetes.io/docs/concepts/architecture/leases/) to do that. This is the same mechanism used by the controllers scaffolded by kube-builder to elect a leader.

Since Poliy Server is written in Rust, we will have to rely on [kubert's lease module](https://docs.rs/kubert/0.22.0/kubert/lease/index.html). These features are not provided by the `kube` crate. However `kubert` is built on top of `kube`, is actively maintained and is used in production by linkerd

2024-12-20 12:02 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +### Shared Policy Cache
Some notes to be added.

We will load the module and precompile it using [`wasmtime::Engine::precompile_module`](https://docs.rs/wasmtime/latest/wasmtime/struct.Engine.html#method.precompile_module). We will then save the binary blob to disk.

The wasmtime `Module` can then loaded by the non-leader instances using the [`wasmtime::Module::deserialize_file`](https://docs.rs/wasmtime/latest/wasmtime/struct.Module.html#method.deserialize_file).

## Limitations

### Compatibility of precompiled modules

A precompiled module can be successfully reused by another `wasmtime::Engine` only if the following conditions are satisfied:

- The same version of wasmtime is used both by the "optimizer" and by the end consumer
- The same `wasmtime::Config` was used both by the "optimizer" and by the end consumer. For example, if we enable [async support](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.async_support) (we plan to do that soon) or [epoch interruption](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.epoch_interruption) (we use that to implement the timeout protection feature) on the consumer side, but the "optimizer" did not have them enabled at compilation time, there will be an error.

This is documented [here](https://docs.rs/wasmtime/latest/wasmtime/struct.Module.html#method.deserialize):

> Note that this function is designed to be safe receiving output from any compiled version of wasmtime itself. This means that it is safe to feed output from older versions of Wasmtime into this function, in addition to newer versions of wasmtime (from the future!). These inputs will deterministically and safely produce an Err. This function only successfully accepts inputs from the same version of wasmtime, but the safety guarantee only applies to externally-defined blobs of bytes, not those defined by any version of wasmtime. (this means that if you cache blobs across versions of wasmtime you can be safely guaranteed that future versions of wasmtime will reject old cache entries).

We can rely on Wasmtime producing an error when we attempt to load an incompatible version of an optimized module (and then just handle that gracefully by downloading and optimizing the module on "our own").
Otherwise, we could save some metadata next to the binary blob, containing the details about the version of wasmtime used and the configuration in place. wasmtime has some built-in mechanism to keep track of its own version when handling modules: see [here](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.module_version).

### Security implications

Loading the precompiled binary blob from the shared cache can expose to a attacks. An attacker could replace the binary blob with another one that, while being valid, is doing something completely different. Basically, we could allow arbitrary code to run.

We can eliminate this risk by using Sigstore signing capability (with simple private keys, no fulcio/rekor involvement) to sign and verify all these binary blobs.
We could leverage the already existing internal CA of Kubewarden to generate a certificate and a key that can be used by the leader to sign the blobs.

2024-12-20 12:02 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +The current policy will be stored in another CRD, similar to the `Policy` CRD, but with a different name, such as `PolicyReplica`.
Naming is hard. I think Replica is not super helpful, what about `PolicyInstance`?

I fear we would have to introduce these lower-level resources for every policy-related CRD we have:

- `AdmissionPolicy`: `AdmissionPolicyInstance`
- `ClusterAdmissionPolicy`: `ClusterAdmissionPolicyInstance`
- `AdmissionPolicyGroup`: `AdmissionPolicyGroupInstance`
- `ClusterAdmissionPolicyGroup`: `ClusterAdmissionPolicyGroupInstance`

2024-12-20 12:02 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +This approach guarantees that the Policy Server will always have a valid policy to load and avoids any service interruptions during updates.
I'm fine with that, I think it's nice. However, I think we need to have more than 1 `PolicyInstance` object per Policy.

Ideally we would need 2 objects. The `PolicyInstance` would have a boolean field `active` and only the ones with `active == true` are going to be served by the Policy Servers.

Let's go through a timeline of events (which is something we should also make part of the RFC):

- User creates a `AdmissionPolicy`
- The leader of the Policy Servers notices that, downloads, optimize and verify the policy.
- The leader creates a `AdmissionPolicyInstance` object with `gen: 1` and `active: true`
- All the policy servers expose the policy as `/validate/<id of the policy>/g1`
- The webhook is created and points to `/validate/<id of the policy>/g1`

The user makes a change to the previously created policy:
- The leader notices the change, downloads, optimizes and verifies the policy
- The leader creates a new `AdmissionPolicyInstance` with `g2` and `active: true`
- All the policy servers expose the new instance of the policy as `/validate/<id of the policy>/g2`. The `/validate/<id of the policy>/g1` is still active
- The kubewarden controller monitors the rollout of the g2 version of the policy. Once this is available on all the instances it updates `AdmissionPolicyInstance(g1)` to have `active: false`
- The policy servers notice the change stop serving the `g1` policy

The user can eventually do a rollback, but this is something we need to think more about...

Thinking more about that, we might not even need the `active

2025-01-09 09:38 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +- `Pending`: The policy is being loaded.
fix this

2025-01-10 13:01 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +The Policy Server will be deployed as a StatefulSet to ensure that each replica has a unique identity.
this was documented in the policy serve lifecycle below

2025-01-10 17:22 UTC, flavio reviewed
looks really good to me

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +This approach allows the Policy Server to manage serve versions of a policy at the same time, facilitating the gradual rollout of updates.
```suggestion
This approach allows the Policy Server to manage multiple generations of a policy at the same time, facilitating the gradual rollout of updates.
```

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +  data: # data will contain the policy content
```suggestion
  data: # data will contain the policy.spec contents
```

I was also thinking we don't need the whole spec, we could also take the module and the settings. But this would not be true for group policies, where other fields are needed.
Long story short, we can just keep it simple and take the whole `.spec` like you are suggesting

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +This will trigger the replica reconciler to load the policy in the evaluation environment in all the replicas.
```suggestion
This will trigger the replica reconciler to load the policy in the evaluation environment of all the policy server pods that are part of the StatefulSet.
```

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +For instance: `/validate/privileged-pods?generation=2` will validate the request against the `privileged-pods` policy with generation 2.
I don't know if the API server can actually use this query parameter. Regardless of that, I prefer to make the generation number part of the URL, a bit like it's done when versioning public REST APIs.

I propose something like that:

```
/validate/privileged-pods/g2
```

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +Being the `PolicyRevision` CRD a namespaced resource, the user might not have the necessary permissions to access it.
Just to make more evident regular users will not be able to access `PolicyRevision`, and that's fine.

```suggestion
Being the `PolicyRevision` CRD a namespaced resource, only admin users will have the right permissions to access it.
```

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +If the `PolicyRevision` is `enabled` but the status condition is not `Initialized`, the Policy Server leader will be in charge of the initlialization process.
```suggestion
If the `PolicyRevision` is `enabled` but the status condition is not `Initialized`, the Policy Server leader will be in charge of the initialization process.
```

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
>  Example: `/cache/ghcr.io/kubewarden/policies/safe-labels/v1.0.0/v1.28.1/module.wasm`.
nitpicking:

```suggestion
Example: `/cache/ghcr.io/kubewarden/policies/safe-labels/v1.0.0/kw-v1.28.1/optimized.wasm`.
```

2025-01-10 17:22 UTC, flavio commented on rfc/0022-policy-lifecycle.md
>  Example: `/cache/ghcr.io/kubewarden/policies/safe-labels/v1.0.0/v1.28.1/module.wasm`.
or:

```suggestion
Example: `/cache/ghcr.io/kubewarden/policies/safe-labels/v1.0.0/optimized-kw-v1.28.1.wasm`.
```

By keeping all the optimized versions of a policy inside of the same folder we could simplify the garbage collector code

2025-01-13 12:28 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +| RFC PR       | [fill this in after opening PR] |
memo to self: fix this

2025-01-14 09:40 UTC, jhkrug requested changes
A few suggestions and occasional typo for your consideration.

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +To implemenet the new policy lifecycle, we will introduce the following concepts:
```suggestion
To implement the new policy lifecycle, we introduce the following concepts:
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +The PolicyRevision will include fields to store the policy content and an `enabled` field to specify whether the policy should be served by the Policy Server.
To match other uses of PolicyRevision.
```suggestion
The `PolicyRevision` will include fields to store the policy content and an `enabled` field to specify whether the policy should be served by the Policy Server.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +causing the pod to enter a CrashLoopBackOff state.
Shorter sentences for readability.

```suggestion
Currently, a policy can fail to load for a variety of reasons. For example, an inability to download from the registry or incorrect settings. This causes the Policy Server to exit with an error, causing the pod to enter a CrashLoopBackOff state.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +However, a user might have the permissions to create a policy but lack the necessary permissions to check the logs of the Policy Server, making it challenging to diagnose and resolve the problem.
Shorter sentences.
```suggestion
However, a user might have the permissions to create a policy but lack the necessary permissions to check the logs of the Policy Server. This presents challenges to diagnosis and resolution of problems.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- Policy validation: The Policy Server will validate the policy before loading it, ensuring that it is correctly compiled and can be loaded.
A few less words. Though I'm trying to be very careful with meaning. It is pre-compilation, right?
```suggestion
- Policy validation: The Policy Server will validate the policy before loading it, ensuring correct pre-compilation and loading.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- Policy status monitoring: The Policy Server will report the status of the policy, indicating whether it was loaded successfully or if an error occurred.
More concise?
```suggestion
- Policy status monitoring: The Policy Server will report the policy's load status.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want to load a new policy/update an existing policy without requiring a restart of the policy server.
```suggestion
- As a user, I want to load a new policy or update an existing policy without requiring a restart of the policy server.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want to know if a policy was pulled or validated successfully.
Maybe? Or does pulled mean withdrawn, in the case of unsuccessful validation. Anyway I wasn't clear what was meant.
```suggestion
- As a user, I want to know if a policy was downloaded and validated successfully.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want to monitor the status of a policy on specific policy server replica so that I can identify and resolve issues with the policy.
```suggestion
- As a user, I want to monitor the status of a policy on a specific policy server replica so that I can identify and resolve issues with the policy.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want that the policy server keeps running with a previous version of the policy in case of issues with the latest policy.
```suggestion
- As a user, I want the policy server to remain running with a previous version of the policy in case of issues with the latest policy.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want to debug issues with the namespaced policies I own without needing to involve the cluster administrator.
More concise?
```suggestion
- As a user, I want to debug issues with the namespaced policies I own without involving the cluster administrator.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +This is will be achieved by refactoring the `EvaluationEnvironment` adding methods to set, update and remove policies.
```suggestion
This will be achieved by refactoring the `EvaluationEnvironment` and adding methods to set, update, and remove policies.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +At the time of writing the Policy Server is configured with a ConfigMap that contains all the policies to be loaded.
```suggestion
Currently, the Policy Server is configured with a ConfigMap that contains all the policies to be loaded.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- `PolicyRevisions` with `enabled` set to `false` represent previous states of the policies, retained for potential rollback scenarios.
```suggestion
- `PolicyRevisions` with `enabled` set to `false` represents previous states of the policies, retained for potential rollback scenarios.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +The data field is of type `RawExtension`, which allows it to store any type of policy.
```suggestion
The data field is of type `RawExtension`, allowing it to store any policy type.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +The Policy Server replicas will be watching the new `PolicyRevision` CRD directly and it will change the internal state of the evaluation environment when a new policy is created or updated.
```suggestion
The Policy Server replicas will be monitoring the new `PolicyRevision` CRD directly and will change the internal state of the evaluation environment when a new policy is created or updated.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +The replicas will be watching the `PolicyRevision` CRDs and load the policy in the evaluation environment when the status condition of type `Initialized` is set to `True` and the `enabled` field is s
```suggestion
The replicas will monitor the `PolicyRevision` CRDs and load the policy in the evaluation environment when the status condition of type `Initialized` is set to `True` and the `enabled` field is set to `true`.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +Being the `PolicyRevision` CRD a namespaced resource, only admin users will have the right permissions to access it.
```suggestion
As the `PolicyRevision` CRD is a namespaced resource, only admin users will have the right permissions to access it.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +
A general note. Consistency. In a sentence, not at the start, use 'Wasmtime' or 'wasmtime', but not both. I'm not sure which one is preferred or correct.

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +Please refer to the [Wasmtime documentation](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.module_version) for more information about module versions strategies.
```suggestion
Please refer to the [Wasmtime documentation](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.module_version) for more information about module version strategies.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +- `Initialized`: The policy was successfully pulled, precompiled and validated by the leader.
Pulled or downloaded again. I would prefer downloaded if that's what meant. I think it's clearer in this context

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +11. The policy is now read to be used.
```suggestion
11. The policy is now ready to be used.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +12. The policy is now read to be used.
```suggestion
12. The policy is now ready to be used.
```

2025-01-14 09:40 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +10. When all the replicas have set the `Ready` status to true, the controller creates updateds the Webhook configuration with the `generation` query parameter set to the `PolicyRevision` generation.
Maybe?
```suggestion
10. When all the replicas have set the `Ready` status to true, the controller creates or updates the Webhook configuration with the `generation` query parameter set to the `PolicyRevision` generation.
```

2025-01-14 11:03 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +`PolicyRevisions` are namespaced resources, and they will be created in the same namespace as the controller.
by controller, we mean the policy-server that serves the policies associated to the PolicyRevision, correct?

2025-01-14 11:04 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +When a new Policy is created, the controller will create a new `PolicyRevision` resource with the policy content and set the `enabled` field to `true`.
the controller here means the policy-server, correct? As in, only policy-servers are controllers for Policies and PolicyRevisions?

2025-01-14 11:11 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +TODO: explain this example
```suggestion
Where `v1.0.0` is the policy version and `v1.28.1` the policy-server version.
```

2025-01-14 11:15 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +To mitigate this risk, we will use [sigstore](https://github.com/sigstore)'s signing capabilities to sign and verify all binary blobs.
We should ensure this is possible offline to be compatible with airgap. Cosign has offline verification, but needs network for signing (see [here](https://github.com/sigstore/cosign/blob/main/README.md#verify-a-container-in-an-air-gapped-environment)).

2025-01-14 11:16 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +By leveraging Kubewarden's internal certificate authority (CA), we can generate a certificate and private key for the leader to sign blobs, ensuring that only trusted and verified blobs are used.
We should ensure this approach works offline for airgap installs by disabling the logs, etc.

2025-01-14 11:44 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +When a new Policy is created, the controller will create a new `PolicyRevision` resource with the policy content and set the `enabled` field to `true`.
the controller means the main golang controller. even if the policy server acts as a controller for policy revision, the first creation is made by the kw controller.

2025-01-14 11:50 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +`PolicyRevisions` are namespaced resources, and they will be created in the same namespace as the controller.
we mean the main controller, the kw controller

2025-01-14 11:51 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +- `Initialized`: The policy was successfully pulled, precompiled and validated by the leader.
@jhkrug I’m considering switching everything to "pulled" since "pulling" is the term commonly used when referring to OCI registries.

2025-01-14 11:55 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +`PolicyRevisions` are namespaced resources, and they will be created in the same namespace as the controller.
I will clarify

2025-01-14 12:00 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +- Policy status monitoring: The Policy Server will report the status of the policy, indicating whether it was loaded successfully or if an error occurred.
I prefer to keep the first version, as it highlights the possibility of an error.

2025-01-14 12:00 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want to know if a policy was pulled or validated successfully.
See https://github.com/kubewarden/rfc/pull/44#discussion_r1914694726

2025-01-14 12:05 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +- As a user, I want to know if a policy was pulled or validated successfully.
```suggestion
- As a user, I want to know if a policy was successfully pulled, precompiled, and validated.
```

2025-01-14 12:19 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +The Policy Server replicas will be watching the new `PolicyRevision` CRD directly and it will change the internal state of the evaluation environment when a new policy is created or updated.
`Watching` is the appropriate term here since the PolicyServer utilizes Kubernetes watches.

2025-01-14 12:20 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +The replicas will be watching the `PolicyRevision` CRDs and load the policy in the evaluation environment when the status condition of type `Initialized` is set to `True` and the `enabled` field is s
see: https://github.com/kubewarden/rfc/pull/44#discussion_r1914726375

2025-01-14 12:44 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +
updated all occurrences to `Wasmtime`

2025-01-14 13:27 UTC, jvanz requested changes

2025-01-14 13:27 UTC, jvanz commented on rfc/0022-policy-lifecycle.md
> +The controller will detect the change and use the `PolicyRevision` CRD to update the Policy CRD with the previous configuration.
Why do the user needs to change a version filed in the CRD? If the `Policy` CRD define the desired state, shouldn't  users just reapply the new state and see if policy server is able to load it? What happen if the user change the `Policy` CRD version field and something else (e.g. settings) ?

2025-01-14 13:27 UTC, jvanz commented on rfc/0022-policy-lifecycle.md
> +11. The policy is now ready to be used.
As now we have two controllers, I think we need to make which of it we are referring to. Just a suggestion:

```suggestion
1. The user creates a new `Policy`.
2. The Kubewarden controller creates a new `PolicyRevision` resource with the policy content and sets the `enabled` field to `true`.
   It also sets the `policyGeneration` field to the value of `metadata.generation` from the `Policy` CRD and adds the `Scheduled` status condition to both the `Policy` and `PolicyRevision` CRDs.
3. The new `PolicyRevision` triggers the policy server leader reconciler. The policy server leader pulls the policy from the registry, precompiles the policy, and stores it in the shared cache.
4. The policy server leader validates the policy settings.
5. The policy server leader changes the status condition of type `Initialized` of the `PolicyRevision` to `True`.
   - If an error occurred in the previous steps, the status condition of type `Initialized` will be set to `False` with the appropriate reason and message.
6. The Kubewarden controller propagates the status condition to the `Policy` CRD.
7. The replica reconciler of all the replicas including the policy server leader loads the policy in the evaluation environment.
8. Every replica will report the status of the policy to the `PolicyRevision` CRD, setting the status condition of type `Ready` to `True`.
   - If an error occurs, the status condition of type `Ready` will be set to `False` with the appropriate reason and message.
9. The `Ready` status is propagated to the `Policy` CRD.
10. When all the replicas have set the `Ready` status to true, the Kubewarden controller creates a Webhook configuration with the `generation` query parameter set to the `PolicyRevision` generation.
11. The policy is now ready to be used.
```

2025-01-14 13:27 UTC, jvanz commented on rfc/0022-policy-lifecycle.md
> +10. When all the replicas have set the `Ready` status to true, the controller creates a Webhook configuration with the `generation` query parameter set to the `PolicyRevision` generation.
If we will update the webhooks only after all the replicas as ready, why do we need to have the generation in the path? On each case the old revision will be used? Is this necessary because the RFC expect to have a revision field in the `Policy` CRD?

2025-01-14 13:32 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +If a policy fails to load, the Policy Server will keep running with the previous valid policy.
I wonder if we can inform the user of this. As it stands, users would need to look at the policy status + generation number, which isn't ergonomic. Maybe we could add a `ReadyButOld` status if the generation is not the last possible.

2025-01-14 13:41 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +If a policy fails to load, the Policy Server will keep running with the previous valid policy.
It would be nice if we can signify the user of this case, so they don't need to look at the ready + generation number.

Maybe adding another condition besides Ready, such as `ReadyButOld`, with reason being `generation-22` for example.

2025-01-14 13:43 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +11. The policy is now ready to be used.
I would also enjoy this clarification please. I thought so far that the policy-server controller would be only for PolicyRevisions.

2025-01-15 08:44 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +By leveraging Kubewarden's internal certificate authority (CA), we can generate a certificate and private key for the leader to sign blobs, ensuring that only trusted and verified blobs are used.
The plan is to use traditional keys to sign and verify the modules. No keyless signing is going to be used.
Also, no rekor integration is going to be leveraged.

2025-01-15 08:58 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +If a policy fails to load, the Policy Server will keep running with the previous valid policy.
I would try to leave the conditions as simple as possible, and then build some logic that uses them to provide meaningful information to the end users.

kubectl gives some control about how the data is shown to the user, but I don't know if we would have enough freedom to implement what I've described.

We could also create a kubewarden kubectl plugin for that. This could also be used to implement subcommands like "rollback" for our policies. AFAIK we cannot extend `kubectl rollback` to handle also our resources.

2025-01-15 09:03 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +The controller will detect the change and use the `PolicyRevision` CRD to update the Policy CRD with the previous configuration.
I think doing a rollback is something tricky. What is described here is not what I would do.

Assuming we want to rollback from generation 2 to generation 1.
We take contents of the `PolicyRevision(g1).spec.data` and copy it back to the `Policy.spec`.

I think we could do a rollback with the set of CRDs described by this RFC. What we have to figure out is if it makes sense to offer this functionality and what the UX would be. I consider that not something to be part of this RFC

2025-01-15 09:12 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +   It also sets the `policyGeneration` field to the value of `metadata.generation` from the `Policy` object and adds the `Scheduled` status condition set to `False` to both the `Policy` and `PolicyRe
Maybe it could also add an event to Policy stating that the policy is being upgraded

2025-01-15 13:38 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +10. When all the replicas have set the `Ready` status to true, the controller creates a Webhook configuration with the `generation` query parameter set to the `PolicyRevision` generation.
The goal is to continue serving the old policy until the new one is fully ready. Without including the generation in the path, any errors in loading the new policy by some replicas would prevent a proper rollout. In the current implementation, the policy remains marked as active because the old version was active, even if the new policy contains errors and the pod is in a CrashLoopBackoff state.

2025-01-15 13:46 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +If a policy fails to load, the Policy Server will keep running with the previous valid policy.
@viccuad, there's another approach used by Pod resources that we could adopt. We could introduce a [`[phase](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase)`](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase) field alongside `status.conditions` to provide a high-level summary of the Policy's lifecycle stage. For example, the phase could include values like `Pending`, `Initializing`, `Active`, `Failed`, or `Updating`, while still displaying a detailed summary of the conditions, such as `Ready 2/3`.

2025-01-15 13:57 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +   It also sets the `policyGeneration` field to the value of `metadata.generation` from the `Policy` object and adds the `Scheduled` status condition set to `False` to both the `Policy` and `PolicyRe
Are you referring to Kubernetes events? [Does this section clarify the purpose of generating events sufficiently?](https://github.com/kubewarden/rfc/blob/c3d4d1e88f3fc837e1e16dfe0356b596d14a4c3d/rfc/0022-policy-lifecycle.md?plain=1#L288)

2025-01-15 16:25 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +11. The policy is now ready to be used.
fixed

2025-01-15 16:25 UTC, fabriziosestito commented on rfc/0022-policy-lifecycle.md
> +If a policy fails to load, the Policy Server will keep running with the previous valid policy.
Added `phase` in https://github.com/kubewarden/rfc/pull/44/commits/5407d80b73a5a533c02ebf8865763fabc42b92df

2025-01-16 13:39 UTC, jvanz approved these changes

2025-01-16 13:39 UTC, jvanz commented on rfc/0022-policy-lifecycle.md
> +9. Thereplica reconciler of all the replicas including the leader loads the policy in the evaluation environment.
```suggestion
9. The replica reconciler of all the replicas including the leader loads the policy in the evaluation environment.
```

2025-01-16 13:39 UTC, jvanz commented on rfc/0022-policy-lifecycle.md
> +This will prevent the cache from growing indefinitely and consuming unnecessary resources.
Considering that we will have a configuration to define the number of revision that will store. Don't the garbage collector need to clean conditions from old generations? I guess there is a limit of the number of conditions allowed, isn't it? 

Even if there is not limits for the conditions count, I believe this is a good  thing to have. It's cleaner and easier to the user to process the data with the want to.

2025-01-17 09:04 UTC, flavio reviewed
Looks really good! We're getting there

2025-01-17 09:04 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +This will prevent the cache from growing indefinitely and consuming unnecessary resources.
When talking about a Policy (ClusterAdmisionPolicy, AdmissionPolicy,...) the RFC is proposes to keep the conditions of the currently active generation (say N) and, when doing an upgrade, alsothe conditions of the freshly created one (N + 1). When the upgrade is done, the old conditions (N before) are removed, and only the ones about the currently active one are kept (which were named N + 1 before).

2025-01-17 09:04 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +### Policy Creation
Sorry to bring "bad" news, the sequence below is correct, but it doesn't take into account the `phases` of the Policy, which is something that has just been added to the RFC

2025-01-17 09:04 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +12. When all the replicas have set the `Ready` status to true, the Kubewarden controller creates a Webhook configuration pointing to the `PolicyRevision` generation.
I don't know why, but I always assumed we would updated the webhook configuration. Do we plan instead to have one webhook configuration per policy **and** generation?

Something like `cluster-psp-privileged-g1`, `cluster-psp-privileged-g2`...

Lookin to the next line, I see you use "update" as verb, hence you agree about keeping only 1 webhook configuration per policy.

2025-01-17 09:04 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +15. The policy is now ready to be used.
We are missing the part where someone, I think the kubewarden-controller, changes changes the `PolicyRevision` instance tied to the previous generation of the policy and sets `enabled` to `false`. As a result the policy servers will stop hosting the old generation of the policy (and maybe even drop a wasm module from memory if possible)

2025-01-17 09:04 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +### Policy Update
Same here, can you add some notes about the phases?

2025-01-17 09:04 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +
```suggestion

## Do not squash everything into a `PolicyRevision`

The proposal from above squashes all the different high level policy CRDs into a single type called `PolicyRevision`.

Another possible take would be to create ad-hoc `-Revision` CRDs:

- `ClusterAdmissionPolicy` -> `ClusterAdmissionPolicyRevision`
- `AdmissionPolicy` -> `AdmissionPolicyRevision`
- `ClusterAdmissionPolicyGroup` -> `ClusterAdmissionPolicyRevisionGroup`
- `AdmissionPolicyGroup` -> `AdmissionPolicyRevisionGroup`

Pros:
  - The mapping policy <-> revision would be more immediate when using tools like `kubectl`
  - The non-admin users would have access to the namespaced `-Revision` objects

Cons:
  - The number of CRDs would double
  - Underneath all these CRDs would be equal, all of them would have the old policy
    inside of a `RawExtension` attribute. Another alternative would be to NOT use
    the `RawExtension`, and instead copy the actual spec of the actual policy into the
    revision. Basically do something like Deployment -> ReplicaSet -> Pod do
  - Non admin users have access to the Revision objects - see next
  - Users (admin and non) might feel entitled to interact with the Revision resources.
    This could lead to unexpected problems. The revision resources are an internal
    implementation detail of Kubewarden, not meant to be touched by users.

## Have `ClusterPolicyRevision` and `PolicyRevision` CRDs

With the current proposal there's just one revision CRD which is namespaced. The cluster wide Policies are mapped to the namespaced revision too.

As an alternative we could create a cluster wide CRD named `ClusterPolicyRevision` that is used to store the revisions of cluster wide policies.

There doesn't seem to be a great advantage in doing that.

Aside from "better clarity", we could take advantage of Kubernetes GC:
- A ClusterPolicyRevision would be `owned by` its cluster-wide policy (be it a `ClusterAdmissionPolicy` or a `ClusterAdmissionPolicyGroup`)
- The removal of the policy would automatically lead to the removal of its associated ClusterPolicyRevisions

With the current proposal, this cleanup process becomes a burden of the Kubewarden controller.

## Move `PolicyRevision` to the namespace where the policy is defined

Building on top of the previous proposal, the `PolicyRevision` resources could be created inside of the very same namespace where their Policy counterparts live; as opposed to what the RFC states, which is to put everything into the namespace where the Kubewarden controller is running.

Also in this case, the main advantage would be to be able to leverage Kubernetes' GC.

The main disadvantage is that regular users would have access to these resources and might cause issues by managing them.
```

2025-01-17 13:40 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +| **replica** (optional) | The replica number reporting the status.                                                            |
I'm struggling to see the status.replica real usefulness. Also, the replica number may point to a different policy-server in the future. I think it would be better to emit events when we change statuses instead as mentioned later.

2025-01-17 13:43 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +### Garbage Collection
We should have in mind also deleting old, N+1, PolicyRevisions.

2025-01-17 13:49 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +12. When all the replicas have set the `Ready` status to true, the Kubewarden controller creates a Webhook configuration pointing to the `PolicyRevision` generation.
Can we ensure we are eventually consistent if the replica numbers shuffle, grow or diminish?

2025-01-17 14:23 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +The `PolicyRevision` will also store the older policy to a maximum of `n` revisions, where `n` is a configurable value.
I think the current design only accounts for 1 old revision, not `n` (or I don't understand the specifics on how the rollback and garbage collection happens).

2025-01-17 14:52 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +[drawbacks]: #drawbacks
Running policy-servers outside of a cluster is not possible anymore.
Running a policy-server for raw policies in the cluster is not possible anymore (as the policies are not loaded via Configmap but via PolicyRevisions).

2025-01-17 14:53 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +[drawbacks]: #drawbacks
```suggestion
[drawbacks]: #drawbacks

- Running policy-servers outside of a cluster is not possible anymore.
- Running a [policy-server for raw policies in the cluster](https://docs.kubewarden.io/howtos/raw-policies#running-a-policy-server-inside-kubernetes-without-the-kubewarden-controller) is not possible anymore (as the policies are not loaded via Configmap but via PolicyRevisions).
- We now enforce an ABI compat on policy-server, as policy-server version is taken into account for Wasm module compatibility.
- The implementation effort is quite big; we need to account for a couple of sprints.
```

2025-01-17 15:11 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +- `Updating`: The policy was updated and is pending to be loaded.
```suggestion
- `Updating`: The policy was `Active` before, has been updated and the updated policy is pending to be loaded. The old revision is still around and being served.
```

2025-01-17 15:45 UTC, jvanz requested changes
We should mention in the RFC that we need to change the audit-scanner to properly select the policy generation when building the endpoint used to send the request to validate a resource in the cluster. Because the validation endpoint in the policy server has generation in the path. As well as mention the policy generation in the reports. 

I would say that the audit-scanner should select the totally ready policy generation when building the request. Ignoring the generation that under the process to be active.

2025-01-17 15:49 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +As the `PolicyRevision` CRD is a namespaced resource, only admin users will have the right permissions to access it.
The Policy could have 2 new spec fields that point to the latest PolicyRevision, and the active PolicyRevision. This may simplify garbage collection, general implementation, and user UI on knowing exactly what Policy is being run (settings, etc).

2025-01-20 09:09 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +   It also sets the `policyGeneration` field to the value of `metadata.generation` from the `Policy` object and adds the `Scheduled` status condition set to `False` to both the `Policy` and `PolicyRe
yes, I was referring to events. I think the linked section is good enough. Closing

2025-01-20 11:20 UTC, flavio commented on rfc/0022-policy-lifecycle.md
> +[drawbacks]: #drawbacks
> - Running policy-servers outside of a cluster is not possible anymore.

That's not true. We can have a cli flag that disables the controller. We already have a flag that disables the kubernetes integration for that scope (running out side of k8s)

> - Running a [policy-server for raw policies in the cluster](https://docs.kubewarden.io/howtos/raw-policies#running-a-policy-server-inside-kubernetes-without-the-kubewarden-controller) is not possible anymore (as the policies are not loaded via Configmap but via PolicyRevisions).

This is still possible. We don't plan to remove the ability to load policies from a `.yaml` file, this is something that however is going to be allowed only when using raw policies.

To summarize: when the policy-server binary is started with the appropriate flag, the k8s integration are going to be disabled (no context aware policies, no loading policies from the new CRD) and the policies will be loaded from a `.yaml` file. 

> - We now enforce an ABI compat on policy-server, as policy-server version is taken into account for Wasm module compatibility.

We [already have](https://github.com/kubewarden/policy-server/blob/4ec01b4e779aace356b421cced842b6b3be67295/src/evaluation/precompiled_policy.rs#L74-L95) ABI compatibility at the policy-server level, but this is for different reasons and is unrelated with this RFC.
This RFC proposes to store the optimized WASM modules to disk and keep track of the version of policy server that generated them. This is done only to reduce the boot time of the policy server process, there's compatibility issue between policies and policy servers. Everything is handled behind the scenes, without the users or the policy developers being affected by it.

> - The implementation effort is quite big; we need to account for a couple of sprints.

Let's make it months :sweat_smile:

2025-01-20 11:22 UTC, flavio commented
> audit-scanner

These are some good points, good catch!

2025-01-20 12:48 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +[drawbacks]: #drawbacks
Indeed, good points. I'm resolving this as nothing to add :).

2025-01-22 11:37 UTC, viccuad commented on rfc/0022-policy-lifecycle.md
> +The `PolicyRevision` will also store the older policy to a maximum of `n` revisions, where `n` is a configurable value.
Resolving, I understand that we just have several PolicyRevisions, one per revision we want.

2025-01-22 11:39 UTC, viccuad reviewed
Looks quite good to me, but before approving I would like to agree on if we will be using annotations to link the Policy and the actual PolicyRevision in use (open comment thread up).

2025-01-22 14:32 UTC, viccuad approved these changes
LGTM!

2025-01-22 14:33 UTC, fabriziosestito commented
@jhkrug, ready for another review pass

2025-01-22 18:26 UTC, jvanz approved these changes
LGTM

2025-01-22 18:26 UTC, jvanz commented on rfc/0022-policy-lifecycle.md
> +```
Just removing this weird spaces in the rendered file
```suggestion
```

2025-01-23 13:59 UTC, jhkrug approved these changes
Two tiny suggestions but lgtm.

2025-01-23 13:59 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +These features are not provided by the `kube-rs` crate, but kubert is built on top of `kube-rs`, is actively maintained, and is used in production by Linkerd.
Other tech mentioned has links so ... maybe?
```suggestion
These features are not provided by the `kube-rs` crate, but kubert is built on top of `kube-rs`, is actively maintained, and is used in production by [Linkerd](https://linkerd.io/).
```

2025-01-23 13:59 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +   It also sets the `policyGeneration` field to the value of `metadata.generation` from the `Policy` CRD and adds the `Scheduled` status condition set to `False` to both the `Policy` and `PolicyRevis
Shorter sentences usually better.
```suggestion
3. The Kubewarden controller creates a new `PolicyRevision` resource with the policy content and sets the `enabled` field to `true`.
   It also sets the `policyGeneration` field to the value of `metadata.generation` from the `Policy` CRD. It adds the `Scheduled` status condition set to `False` to both the `Policy` and `PolicyRevision` CRDs.
```

2025-01-23 13:59 UTC, jhkrug commented on rfc/0022-policy-lifecycle.md
> +```mermaid
Nice sequence diagrams!

2025-01-23 15:56 UTC, merged